// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WineApp.Models;

public partial class Wines
{
    public int WineId { get; set; }

    public string Name { get; set; }

    public int WineType { get; set; }
}