// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WineApp.Models;

public partial class WineType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }
}