// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WineApp.Data;
using WineApp.Models;

namespace WineApp.Data.Configurations
{
    public partial class WinesConfiguration : IEntityTypeConfiguration<Wines>
    {
        public void Configure(EntityTypeBuilder<Wines> entity)
        {
            entity.HasKey(e => e.WineId);
            entity.Property(e => e.WineType).HasConversion<int>();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Wines> entity);
    }
}
